server:
  port: 8099

# Database connection properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Darwin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
